version: '3.8'

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www
            - ./src/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
            - db
    #Database Service
    db:
        image: mysql
        container_name: mysql
        volumes:
            - ./mysql/data:/var/lib/mysql
        ports:
            - "3306:3306"

        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    #    db:
    #        image: postgres
    #        container_name: postgres
    #        volumes:
    #            - ./postgresql/data:/var/lib/postgresql/data
    #        ports:
    #            - "5432:5432"
    #        environment:
    #            POSTGRES_DB: blog
    #            POSTGRES_USER: root
    #            POSTGRES_PASSWORD: password

    # Application Service
    #    app:
    #        container_name: blog
    #        build:
    #            context: ./php
    #            dockerfile: Dockerfile
    #        volumes:
    #            - ./src:/var/www
    #        ports:
    #            - "9000:9000"
    #        working_dir: /var/www

    #phpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "3400:80"
        depends_on:
            - db
    #    pgadmin:
    #        image: dpage/pgadmin4
    #        container_name: pgAdmin
    #        ports:
    #            - "5050:80"
    #        depends_on:
    #            - db
    #        environment:
    #            PGADMIN_DEFAULT_EMAIL: dinhngochai1900@gmail.com
    #            PGADMIN_DEFAULT_PASSWORD: password
    app:
        container_name: website_news
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/website-new
        ports:
            -   "8000:8000"
        working_dir: /var/www/website-new



